"""File module for OpenCode."""

from file.file import (
    FileInfo,
    FileWatchEvent,
    read_file,
    write_file,
    read_file_binary,
    write_file_binary,
    file_exists,
    is_file,
    is_directory,
    get_file_info,
    list_directory,
    walk_directory,
    copy_file,
    copy_directory,
    move_file,
    delete_file,
    delete_directory,
    create_directory,
    get_file_lines,
    tail_file,
    watch_file,
    is_binary,
    get_text_encoding,
)

__all__ = [
    "FileInfo",
    "FileWatchEvent",
    "read_file",
    "write_file",
    "read_file_binary",
    "write_file_binary",
    "file_exists",
    "is_file",
    "is_directory",
    "get_file_info",
    "list_directory",
    "walk_directory",
    "copy_file",
    "copy_directory",
    "move_file",
    "delete_file",
    "delete_directory",
    "create_directory",
    "get_file_lines",
    "tail_file",
    "watch_file",
    "is_binary",
    "get_text_encoding",
]
